### ISSUE TITLE
blog post preparation

### ISSUE THREAD

**Issue by merando** [IIDP/OSTMap#46]
After Milestone 1 we can gather information for the tech blog post.
### Task

Discuss which information and findings are suitable for a tech blog post. 
While discussing try to ask youself:
- What would I like to read about OSTMap?
- What is/was challenging?
- What differs from a classic relational environment?
- What can we do next to enhance OSTMap?
- ...

**Comment by martingrimmer** [comment]
@CSchott @HansPog whats the current status?

**Comment by CSchott** [comment]
Hans added his text yesterday in the evening. I plan to modify the text today, so it should be finished today in the evening/ tomorrow morning.

**Comment by CSchott** [comment]
I worked on the blog post and would be glad if anyone could review it and give me some advise. I put all the information in it, that was given to me by the teammembers. There are some todos for @kev007 still in the texts. Didn't know what to do with it. I changed them a bit so that there are no occurances of i and my in it. If you have anything to add or to change, please let me know, so that i can change it accordingly.

**Comment by merando** [comment]
hey @CSchott . the docs link does not work anymore. Can you please provide a new one?

**Comment by merando** [comment]
I had a first short glance and it looked ok :)

**Comment by martingrimmer** [comment]
draft accepted -> closed
